export type LibraryRecipe = {
  id: string;
  name: string;
  prepTime: string;
  servings: number;
  ingredients: string[];
  steps: string[];
};

export type LibraryCategory = {
  id: string;
  label: string;
  emoji: string;
  recipes: LibraryRecipe[];
};

// ─── Pratos Principais ────────────────────────────────────────────────────────
const pratosPrincipais: LibraryRecipe[] = [
  {
    id: "abobora-cremosa-carne-seca",
    name: "Abóbora Cremosa com Carne Seca",
    prepTime: "30 min",
    servings: 6,
    ingredients: [
      "500 g de abóbora japonesa picada",
      "1/2 colher (sopa) de óleo",
      "1/2 colher (chá) de sal",
      "500 g de carne-seca cozida e desfiada",
      "1 lata (300 g) de creme de leite",
    ],
    steps: [
      "Em uma panela, refogue a abóbora no óleo e adicione o sal. Refogue até que fique cozida, porém firme.",
      "Junte a carne-seca e o creme de leite e misture bem.",
      "Coloque em um refratário médio (20×30 cm) e leve ao forno médio-alto (200 °C), pré-aquecido, por 15 minutos para gratinar.",
      "Sirva a seguir.",
    ],
  },
  {
    id: "bife-de-marinheiro",
    name: "Bife de Marinheiro",
    prepTime: "50 min",
    servings: 6,
    ingredients: [
      "500 g de coxão mole em bifes pequenos",
      "4 batatas grandes em rodelas",
      "2 cebolas em rodelas",
      "4 tomates em rodelas",
      "4 tabletes de caldo de carne",
      "1/2 copo de vinho branco seco",
      "Azeite para regar",
      "Sal a gosto",
    ],
    steps: [
      "Coloque um fio de azeite em uma panela de fundo largo.",
      "Distribua camadas alternadas de bife, tomate, cebola e batata.",
      "Dissolva os tabletes de caldo em 1/2 xícara (chá) de água fervente, acrescente o vinho e misture.",
      "Espalhe metade deste líquido sobre a primeira camada. Regue com azeite. Repita as camadas, despeje o restante do líquido e regue novamente.",
      "Tampe a panela e leve ao fogo baixo por aproximadamente 40 minutos. Sirva a seguir.",
    ],
  },
  {
    id: "bifes-recheados-especiais",
    name: "Bifes Recheados Especiais",
    prepTime: "1h",
    servings: 4,
    ingredients: [
      "500 g de alcatra em bifes",
      "1 xícara (chá) de brócolis aferventado e picado",
      "1 cebola picada",
      "100 g de mussarela ralada",
      "1/2 colher (chá) de sal",
      "1 tablete de caldo de carne",
      "1 colher (sopa) de óleo",
      "4 colheres (sopa) de vinho tinto seco",
      "1 colher (sopa) de maisena",
    ],
    steps: [
      "Misture o brócolis, a cebola, a mussarela e o sal. Reserve.",
      "Polvilhe metade do caldo esfarelado sobre os bifes e recheie cada um com a mistura. Enrole, fechando as laterais, e prenda com palito ou barbante.",
      "Em panela de pressão, aqueça o óleo e doure os bifes. Junte o vinho, o restante do caldo dissolvido em 2 xícaras de água fervente. Tampe e cozinhe em fogo médio por 40 minutos.",
      "Espere sair a pressão, abra a panela e retire os bifes. Dissolva a maisena em 2 colheres de água fria e junte ao caldo. Deixe ferver, mexendo até engrossar.",
      "Despeje o molho sobre os bifes e sirva.",
    ],
  },
  {
    id: "files-molho-ameixas",
    name: "Filés com Molho de Ameixas",
    prepTime: "30 min",
    servings: 4,
    ingredients: [
      "500 g de filé mignon em medalhões",
      "1 cebola ralada",
      "1 tablete de caldo de carne",
      "2 colheres (sopa) de azeite",
      "1 xícara (chá) de vinho tinto seco",
      "1/2 xícara (chá) de ameixas pretas sem caroço",
      "Sal e pimenta a gosto",
    ],
    steps: [
      "Tempere os filés com a cebola ralada e o caldo esfarelado. Reserve.",
      "Em uma frigideira, aqueça o azeite e doure os filés. Reserve e mantenha aquecido.",
      "Na mesma frigideira, junte o vinho, o caldo dissolvido em 1/2 xícara de água quente e as ameixas. Cozinhe por cerca de 5 minutos ou até as ameixas ficarem macias.",
      "Despeje o molho sobre os filés e sirva a seguir.",
    ],
  },
  {
    id: "salada-de-carne",
    name: "Salada de Carne",
    prepTime: "45 min",
    servings: 4,
    ingredients: [
      "500 g de músculo cozido e desfiado",
      "1 cebola picada",
      "1 colher (sopa) de tempero grill (mistura de ervas)",
      "2 colheres (sopa) de salsa picada",
      "4 colheres (sopa) de azeite",
      "3 colheres (sopa) de suco de limão",
      "1 pimentão verde em tiras",
      "2 tomates sem pele e sem sementes, picados",
      "1/2 xícara (chá) de azeitonas verdes",
      "6 folhas de alface lisa",
      "4 pães sírios torrados",
    ],
    steps: [
      "Misture bem a cebola, o tempero, a salsa, o azeite e o suco de limão para formar o molho.",
      "Junte a carne desfiada, o pimentão, o tomate e as azeitonas. Misture cuidadosamente.",
      "Em uma travessa, faça um leito com as folhas de alface e disponha a salada de carne no centro.",
      "Sirva a seguir com as torradas de pão sírio.",
    ],
  },
  {
    id: "cozido-brasileiro",
    name: "Cozido Brasileiro",
    prepTime: "1h",
    servings: 6,
    ingredients: [
      "500 g de braço ou acém cortado em cubos",
      "2 colheres (sopa) de óleo",
      "1/2 cebola picada",
      "2 dentes de alho amassados",
      "2 colheres (sopa) de farinha de trigo",
      "2 tabletes de caldo de carne",
      "4 batatas médias cortadas em pedaços",
      "2 cenouras médias cortadas em pedaços",
      "1 xícara (chá) de vagem picada",
      "2 colheres (sopa) de salsa picada",
    ],
    steps: [
      "Em panela de pressão, aqueça o óleo e refogue a cebola e o alho.",
      "Passe os cubos de carne na farinha de trigo e deixe dourar na panela.",
      "Junte os tabletes de caldo dissolvidos em 500 ml de água fervente, a batata e a cenoura. Feche e cozinhe em fogo baixo por 10 minutos após fervura.",
      "Espere sair a pressão, abra a panela e acrescente a vagem. Cozinhe, sem tampar, por mais 30 minutos ou até apurar o caldo.",
      "Retire do fogo, adicione a salsa e sirva.",
    ],
  },
  {
    id: "rocambole-carne-moida",
    name: "Rocambole de Carne Moída",
    prepTime: "1h",
    servings: 5,
    ingredients: [
      "500 g de carne moída",
      "1 ovo",
      "1 envelope de sopa creme de cebola",
      "4 batatas médias",
      "100 g de presunto fatiado",
      "2 colheres (sopa) de azeitonas pretas picadas",
      "Manteiga para untar",
    ],
    steps: [
      "Cozinhe as batatas até ficarem macias. Descasque e passe pelo espremedor ainda quentes. Reserve o purê.",
      "Em uma tigela, misture a carne moída, o ovo e a sopa creme de cebola até obter uma massa firme.",
      "Abra a massa em cima de um filme plástico, formando um retângulo. Disponha as fatias de presunto, espalhe o purê de batatas e as azeitonas.",
      "Enrole como rocambole com ajuda do filme e coloque em assadeira untada. Distribua pedaços de manteiga por cima.",
      "Asse em forno médio (180 °C), pré-aquecido, por cerca de 40 minutos ou até dourar. Sirva a seguir.",
    ],
  },
  {
    id: "lombo-dourado-abacaxi",
    name: "Lombo Dourado com Abacaxi",
    prepTime: "3h",
    servings: 12,
    ingredients: [
      "2 kg de lombo de porco",
      "3 colheres (sopa) de tempero grill (mistura de ervas)",
      "2 xícaras (chá) de vinho branco seco",
      "Suco de 2 limões",
      "1 xícara (chá) de açúcar",
      "1 abacaxi em rodelas",
      "250 g de mini-cebola (cebola-pérola)",
    ],
    steps: [
      "Com a ponta de uma faca, faça pequenos furos na superfície do lombo. Tempere com o tempero grill, coloque em assadeira e junte o vinho e o limão.",
      "Cubra com papel-alumínio e leve à geladeira por cerca de 2 horas, regando com o caldo a cada 30 minutos.",
      "Asse coberto com papel-alumínio em forno médio-alto (200 °C) por 1 hora, regando de vez em quando. Retire o papel e asse por mais 1 hora ou até dourar.",
      "Em uma frigideira, aqueça o açúcar até caramelizar. Junte o abacaxi e a mini-cebola e cozinhe por 5 minutos até dourar.",
      "Sirva o lombo fatiado com o abacaxi e a mini-cebola caramelizados.",
    ],
  },
  {
    id: "hamburguer-caseiro-com-tomate",
    name: "Hambúrguer Caseiro com Tomate",
    prepTime: "30 min",
    servings: 5,
    ingredients: [
      "500 g de carne moída",
      "1 tablete de caldo de carne",
      "1 colher (sopa) de azeite",
      "2 colheres (sopa) de cebola picada",
      "4 tomates picados em cubos pequenos",
      "1 pitada de açúcar",
      "1/2 colher (sopa) de tempero em pó a gosto",
      "1 colher (sopa) de manjericão fresco picado",
      "Óleo para untar",
    ],
    steps: [
      "Em uma tigela, misture a carne moída com o caldo dissolvido em 3 colheres de água quente até ficar uniforme.",
      "Modele os hambúrgueres. Unte uma frigideira com óleo e doure aos poucos. Reserve em local aquecido.",
      "Na mesma frigideira, aqueça o azeite e doure a cebola. Junte os tomates, o açúcar e o tempero. Cozinhe em fogo baixo por 10 minutos até o tomate ficar macio.",
      "Misture o manjericão e sirva o molho sobre os hambúrgueres.",
    ],
  },
  {
    id: "strogonoff-classico",
    name: "Strogonoff Clássico",
    prepTime: "35 min",
    servings: 10,
    ingredients: [
      "1 kg de filé mignon (ou alcatra) em tiras finas",
      "4 colheres (sopa) de manteiga",
      "2 cebolas picadas",
      "1/2 colher (sopa) de sal",
      "1 pitada de pimenta-do-reino moída",
      "1/2 xícara (chá) de conhaque",
      "200 g de champignons em conserva fatiados",
      "3 colheres (sopa) de purê de tomate",
      "1 colher (sopa) de mostarda",
      "2 colheres (sopa) de catchup",
      "1 lata (300 g) de creme de leite",
    ],
    steps: [
      "Derreta 3 colheres de manteiga em frigideira grande e frite a carne aos poucos em fogo alto, sem deixar juntar o suco. Reserve.",
      "Na mesma frigideira, adicione a manteiga restante e doure a cebola. Junte a carne, tempere com sal e pimenta e despeje o conhaque.",
      "Incline levemente a frigideira para que o conhaque incendeie. Aguarde a chama apagar.",
      "Junte os champignons, tampe e deixe por alguns minutos. Acrescente o purê de tomate, a mostarda e o catchup. Mexa bem.",
      "Abaixe o fogo, tampe e cozinhe por mais 5 minutos. Incorpore o creme de leite delicadamente e retire do fogo antes de ferver. Sirva com arroz branco.",
    ],
  },
  {
    id: "espetinhos-file-legumes",
    name: "Espetinhos de Filé e Legumes",
    prepTime: "20 min",
    servings: 2,
    ingredients: [
      "300 g de filé mignon em pedaços",
      "1 cebola cortada em quatro",
      "2 tomates sem sementes em cubos",
      "1 colher (sopa) de suco de limão",
      "1 colher (sopa) de tempero grill (mistura de ervas)",
      "1 colher (sopa) de manteiga",
      "2 colheres (sopa) de salsa picada",
    ],
    steps: [
      "Em espetos de metal ou madeira, intercale pedaços de carne com cebola e tomate. Regue com limão e tempere com o tempero grill. Reserve.",
      "Em frigideira grande, aqueça a manteiga e doure os espetinhos. Reserve aquecido.",
      "Na mesma frigideira, junte 1/2 xícara de água e deixe ferver até ficar levemente encorpado. Adicione a salsa.",
      "Sirva o molho quente sobre os espetinhos.",
    ],
  },
  {
    id: "rocambole-frango-recheado",
    name: "Rocambole de Frango Recheado",
    prepTime: "1h10",
    servings: 5,
    ingredients: [
      "4 filés de peito de frango (cerca de 600 g)",
      "1 cebola pequena ralada",
      "2 colheres (sopa) de manteiga",
      "4 fatias de bacon defumado",
      "1 colher (sopa) de farinha de trigo",
      "Sal e tempero completo a gosto",
      "— Para a farofa —",
      "1 xícara (chá) de abóbora aferventada em cubos pequenos",
      "1 pacote de biscoito água e sal triturado",
      "2 colheres (sopa) de salsa picada",
      "1 colher (sopa) de manteiga",
    ],
    steps: [
      "Farofa: aqueça a manteiga, acrescente a abóbora, o biscoito triturado e a salsa. Desligue o fogo e reserve.",
      "Abra os filés deixando-os com espessura fina. Tempere com sal e a cebola ralada.",
      "Corte um retângulo de papel-alumínio (~40×30 cm) e espalhe metade da manteiga. Arrume os filés lado a lado formando um retângulo. Coloque o bacon por cima e espalhe a farofa (sem chegar às bordas). Enrole com ajuda do papel e feche bem as extremidades.",
      "Coloque em assadeira e asse em forno médio (180 °C) por 30 minutos. Retire o papel e retorne ao forno para dourar.",
      "Leve a assadeira à chama do fogão. Acrescente a manteiga restante e a farinha, misture bem e junte 1 xícara de água. Deixe ferver até formar molho espesso. Sirva sobre o rocambole fatiado.",
    ],
  },
  {
    id: "jardineira-de-frango",
    name: "Jardineira de Frango",
    prepTime: "30 min",
    servings: 6,
    ingredients: [
      "1 kg de peito de frango em tiras",
      "3 colheres (sopa) de azeite",
      "Sal e tempero completo a gosto",
      "250 g de cenouras em tiras",
      "250 g de ervilha torta",
      "5 talos de salsão em tiras",
    ],
    steps: [
      "Aqueça o azeite em uma panela. Acrescente o frango, tempere a gosto e deixe dourar.",
      "Junte 1/2 xícara de água e a cenoura. Cozinhe por alguns minutos.",
      "Acrescente a ervilha torta e o salsão. Refogue, mexendo até os legumes ficarem cozidos e ainda crocantes. Pingue água se necessário.",
      "Acerte o sal e sirva a seguir.",
    ],
  },
  {
    id: "frango-vinho-alecrim",
    name: "Frango no Vinho e Alecrim",
    prepTime: "1h (+ marinada)",
    servings: 4,
    ingredients: [
      "1 kg de sobrecoxas de frango desossadas",
      "2 colheres (sopa) de tempero em pó a gosto",
      "1 xícara (chá) de vinho branco seco",
      "2 colheres (sopa) de azeite",
      "1 raminho de alecrim fresco",
    ],
    steps: [
      "Na véspera, misture as sobrecoxas com o tempero, o vinho, o azeite e o alecrim. Cubra e deixe marinando na geladeira, virando os pedaços de vez em quando.",
      "No dia seguinte, coloque os pedaços de frango na grelha e asse até dourarem por completo.",
      "Para saber se está pronto, espete o frango — o suco que sair deve ser transparente.",
    ],
  },
  {
    id: "frango-a-passarinho",
    name: "Frango à Passarinho",
    prepTime: "25 min",
    servings: 4,
    ingredients: [
      "500 g de frango cortado em pequenos pedaços",
      "1/2 colher (sopa) de tempero em pó a gosto",
      "1/2 colher (sopa) de suco de limão",
      "Óleo para fritar",
    ],
    steps: [
      "Com pelo menos 1 hora de antecedência, tempere os pedaços de frango com o tempero e o suco de limão. Deixe tomar gosto.",
      "Aqueça bem o óleo em uma frigideira funda e frite os pedaços de frango até ficarem dourados e crocantes.",
      "Escorra em papel absorvente e sirva a seguir.",
    ],
  },
  {
    id: "farofa-de-miudos",
    name: "Farofa de Miúdos",
    prepTime: "40 min",
    servings: 6,
    ingredients: [
      "150 g de coração de galinha picados",
      "150 g de moelas picadas",
      "100 g de fígado de galinha em tiras",
      "1 colher (sopa) de azeite",
      "1 tablete de caldo de galinha",
      "1 dente de alho picado",
      "1 cebola picada",
      "1/2 xícara (chá) de vinho branco seco",
      "4 colheres (sopa) de azeitonas verdes picadas",
      "2 xícaras (chá) de farinha de mandioca torrada",
      "2 colheres (sopa) de cheiro-verde picado",
    ],
    steps: [
      "Aqueça o azeite e doure os miúdos, acrescentando água aos poucos até que estejam macios.",
      "Junte o caldo esfarelado, o alho, a cebola e o vinho. Deixe reduzir.",
      "Acrescente as azeitonas e a farinha de mandioca. Mexa até obter uma farofa úmida.",
      "Adicione o cheiro-verde, retire do fogo e sirva a seguir.",
    ],
  },
  {
    id: "frango-indiano",
    name: "Frango Indiano ao Curry",
    prepTime: "40 min",
    servings: 6,
    ingredients: [
      "2 peitos de frango em cubos",
      "1 colher (chá) de azeite",
      "2 cebolas em cubos",
      "1 pimentão vermelho em cubos",
      "2 tabletes de caldo de legumes",
      "1/2 colher (chá) de curry",
      "1 colher (chá) de gengibre ralado",
      "1 colher (sopa) de farinha de trigo",
      "1 pote (170 g) de iogurte natural",
      "1/2 lata (150 g) de creme de leite",
      "1 colher (sopa) de cebolinha-verde picada",
    ],
    steps: [
      "Em uma panela, aqueça o azeite e refogue levemente o frango.",
      "Acrescente a cebola, o pimentão e o caldo dissolvido em 1 xícara de água fervente.",
      "Junte o curry, o gengibre e a farinha de trigo. Mexa bem e deixe ferver.",
      "Retire do fogo, acrescente o iogurte e o creme de leite. Misture para incorporar e sirva com a cebolinha polvilhada por cima.",
    ],
  },
  {
    id: "frango-escondidinho",
    name: "Frango Escondidinho",
    prepTime: "1h",
    servings: 8,
    ingredients: [
      "1 kg de mandioca",
      "500 g de peito de frango",
      "2 tabletes de caldo de galinha",
      "1 cebola média ralada",
      "1 colher (sopa) de salsa picada",
      "Sal a gosto",
      "1 lata (300 g) de creme de leite",
      "2 copos (400 g) de requeijão cremoso",
      "2 colheres (sopa) de queijo parmesão ralado",
      "Manteiga para untar",
    ],
    steps: [
      "Descasque, lave e cozinhe a mandioca coberta com água até ficar macia.",
      "Enquanto isso, cozinhe o peito de frango em 1 xícara de água fervente com o caldo, pingando mais água se necessário. Desfie o frango e misture o caldo restante, a cebola e a salsa. Reserve.",
      "Escorra a mandioca e passe-a ainda quente pelo espremedor. Tempere com sal, acrescente o creme de leite e misture bem até obter um purê.",
      "Em um refratário (20×30 cm) untado, espalhe o purê de mandioca e, por cima, o recheio de frango.",
      "Cubra com o requeijão, polvilhe o parmesão e leve ao forno médio-alto (200 °C) para gratinar por cerca de 20 minutos. Sirva a seguir.",
    ],
  },
  {
    id: "frango-a-pizzaiolo",
    name: "Frango à Pizzaiolo",
    prepTime: "30 min",
    servings: 4,
    ingredients: [
      "500 g de filé de frango",
      "1 colher (sopa) de suco de limão",
      "1 colher (sopa) de óleo",
      "1 tablete de caldo de galinha",
      "3 tomates sem pele e sem sementes em cubos",
      "2 colheres (chá) de orégano",
      "3 bolas de mussarela de búfala em rodelas",
    ],
    steps: [
      "Regue o frango com o suco de limão.",
      "Em uma frigideira, aqueça o óleo com o caldo esfarelado e doure o frango. Reserve aquecido.",
      "Na mesma frigideira, refogue levemente o tomate com o orégano.",
      "Misture o queijo e despeje sobre o frango. Leve ao forno médio (180 °C) para derreter. Sirva a seguir.",
    ],
  },
  {
    id: "frango-ensopado",
    name: "Frango Ensopado",
    prepTime: "40 min",
    servings: 4,
    ingredients: [
      "500 g de frango em pedaços (coxa ou sobrecoxa)",
      "Suco de 1/2 limão",
      "1 colher (sopa) de óleo",
      "1 cenoura em rodelas finas",
      "1 tablete de caldo de galinha",
      "1 colher (sopa) de farinha de trigo",
      "1/2 xícara (chá) de vagem picada",
      "1 cebola pequena em rodelas",
      "1/2 alho-poró em rodelas finas",
      "1 colher (sopa) de salsa picada",
    ],
    steps: [
      "Retire a pele do frango, lave e regue com o limão. Doure no óleo quente.",
      "Junte a cenoura e o caldo dissolvido em 1/2 xícara de água. Polvilhe a farinha aos poucos e acrescente mais 1 xícara de água, mexendo sempre.",
      "Tampe a panela e cozinhe até o frango ficar macio.",
      "Adicione a vagem, a cebola e o alho-poró. Cozinhe por cerca de 10 minutos com os legumes macios.",
      "Retire do fogo, misture a salsa e sirva a seguir.",
    ],
  },
  {
    id: "frango-com-laranja",
    name: "Frango com Laranja",
    prepTime: "1h20",
    servings: 4,
    ingredients: [
      "500 g de peito de frango",
      "1 tablete de caldo de galinha",
      "1 colher (sopa) de manteiga em temperatura ambiente",
      "1/2 xícara (chá) de suco de laranja",
      "1 colher (sopa) de salsa picada",
    ],
    steps: [
      "Misture com um garfo o caldo esfarelado com a manteiga até obter uma pasta. Espalhe sobre o frango.",
      "Asse em forno médio-alto (200 °C) por cerca de 40 minutos ou até dourar levemente.",
      "Regue com o suco de laranja e retorne ao forno por mais 20 minutos até dourar bem.",
      "Retire o frango da assadeira e leve a assadeira ao fogo alto. Raspe o fundo com uma colher e deixe o molho ferver até encorpar. Salpique a salsa sobre o frango e sirva com o molho à parte.",
    ],
  },
];

// ─── Doces e Sobremesas (sem açúcar) ──────────────────────────────────────────
const docesSemAcucar: LibraryRecipe[] = [
  {
    id: "abacaxi-assado",
    name: "Abacaxi Assado",
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "4 rodelas grossas de abacaxi",
      "4 colheres (sopa) de suco de abacaxi",
      "1 pitada de canela em pó",
      "1 pitada de cravo em pó",
      "1 colher (sopa) de adoçante natural",
      "1 colher (sopa) de castanha de caju picada",
    ],
    steps: [
      "Disponha as rodelas de abacaxi em uma assadeira.",
      "Misture o suco de abacaxi, adoçante, canela e cravo e regue sobre os abacaxis.",
      "Leve ao forno pré-aquecido e asse levemente por 10 minutos.",
      "Salpique as castanhas e sirva ainda quente, acompanhado de sorvete.",
    ],
  },
  {
    id: "arroz-doce-sem-acucar",
    name: "Arroz Doce",
    prepTime: "40 min",
    servings: 1,
    ingredients: [
      "1/2 xícara de arroz integral",
      "2 xícaras de água",
      "1 pedaço de canela",
      "2 cravos-da-índia",
      "2 colheres (sopa) de leite em pó desnatado",
      "1 maçã doce pequena ralada",
      "3 colheres (chá) de água de flor de laranjeira",
      "Canela em pó a gosto",
      "6 envelopes de stevia",
      "2 gemas",
    ],
    steps: [
      "Cozinhe o arroz com a água, a canela, os cravos e a maçã.",
      "Acrescente o leite em pó e cozinhe por mais 5 minutos.",
      "Retire do fogo, separe a canela e os cravos e deixe amornar.",
      "Junte as gemas desfeitas em um pouco de leite e coe em peneira fina. Misture rapidamente.",
      "Leve novamente ao fogo brando, mexendo até obter um creme espesso.",
      "Fora do fogo, acrescente a água de flor de laranjeira e a stevia. Sirva em taças e polvilhe canela.",
    ],
  },
  {
    id: "beijinho-de-colher",
    name: "Beijinho de Colher",
    prepTime: "1h30",
    servings: 2,
    ingredients: [
      "1 xícara de leite em pó desnatado",
      "50 g de coco fresco ralado em flocos grossos",
      "1/2 xícara de água quente",
      "1 colher (chá) de xylitol ou adoçante natural",
      "5 gotas de essência de baunilha",
    ],
    steps: [
      "Bata no liquidificador o leite em pó com a água quente. Junte a baunilha e o xylitol.",
      "Coloque em um recipiente, acrescente o coco e misture.",
      "Leve à geladeira por 1 hora (ou 15 min no congelador) e está pronto.",
    ],
  },
  {
    id: "biscoito-de-amendoas",
    name: "Biscoito de Amêndoas",
    prepTime: "30 min",
    servings: 6,
    ingredients: [
      "1 xícara de farinha de amêndoas",
      "1/4 xícara de néctar de coco",
    ],
    steps: [
      "Misture os dois ingredientes e amasse bem até formar massa homogênea.",
      "Faça uma bola e leve à geladeira por 15 minutos.",
      "Abra a massa entre duas folhas de papel manteiga com um rolo, deixando bem fina.",
      "Corte no formato desejado e arrume em assadeira forrada. Asse a 180 °C por 10-13 minutos até dourar nas laterais.",
      "Deixe esfriar sobre uma grade — é nesse momento que ficam crocantes.",
    ],
  },
  {
    id: "biscoito-de-aveia",
    name: "Biscoito de Aveia",
    prepTime: "30 min",
    servings: 6,
    ingredients: [
      "4 claras de ovo",
      "120 g de flocos de aveia",
      "1 colher (café) de essência de baunilha",
      "1 pitada de estévia",
      "1 pitada de canela em pó",
      "1 pitada de sal",
      "2 colheres (sopa) de leite de amêndoa",
    ],
    steps: [
      "Bata no liquidificador os flocos de aveia e as claras até virar uma pasta úmida.",
      "Coloque em uma tigela, acrescente a estévia, sal, baunilha, canela e o leite. Misture bem.",
      "Modele os biscoitos com as mãos em formato redondo.",
      "Em frigideira untada com um fio de azeite, doure os biscoitos dos dois lados até ficarem cozidos.",
      "Sirva com um pouco de mel e morangos, se desejar.",
    ],
  },
  {
    id: "biscoito-de-chocolate",
    name: "Biscoito de Chocolate",
    prepTime: "30 min",
    servings: 5,
    ingredients: [
      "1/2 xícara de stévia em pó",
      "125 g de manteiga",
      "3 ovos",
      "125 g de farinha de arroz",
      "1 colher (café) de extrato de baunilha",
      "30 g de cacau em pó",
    ],
    steps: [
      "Bata os ovos, a baunilha e a stévia até ter espuma na superfície.",
      "Em outra tigela, misture a farinha de arroz com o cacau em pó.",
      "Adicione as farinhas aos ovos em velocidade baixa até obter massa homogênea.",
      "Acrescente a manteiga derretida e continue batendo até incorporar.",
      "Coloque pequenas bolas achatadas em assadeira untada e polvilhada. Asse a 180 °C por 15 minutos. Deixe esfriar completamente.",
    ],
  },
  {
    id: "biscoito-de-coco",
    name: "Biscoito de Coco",
    prepTime: "30 min",
    servings: 4,
    ingredients: [
      "2 bananas maduras",
      "100 g de coco ralado (1/4 xícara)",
      "1/2 xícara de uva-passa",
    ],
    steps: [
      "Amasse as bananas até obter uma pasta macia.",
      "Acrescente o coco ralado e mexa até incorporar.",
      "Em assadeira com papel manteiga, distribua porções circulares da massa. Coloque uva-passa por cima.",
      "Asse em forno pré-aquecido a 180 °C por 20 minutos ou até dourar nas laterais.",
      "Deixe esfriar alguns minutos antes de servir.",
    ],
  },
  {
    id: "bolo-de-ameixa",
    name: "Bolo de Ameixa",
    prepTime: "1h",
    servings: 6,
    ingredients: [
      "100 g de ameixas secas sem caroço picadas",
      "200 ml de chá de hortelã",
      "1/2 xícara (chá) de adoçante culinário natural",
      "6 colheres (sopa) de margarina light",
      "1 e 1/2 xícara (chá) de farinha de coco",
      "1 colher (sopa) de fermento em pó",
      "1/2 xícara (chá) de aveia em flocos",
      "3 ovos (gemas e claras separadas)",
    ],
    steps: [
      "Cozinhe as ameixas com o chá de hortelã e o adoçante por 15 minutos até ficarem macias. Deixe amornar.",
      "Na batedeira, bata as ameixas com as gemas e a margarina por 5 minutos.",
      "Acrescente aos poucos a farinha de coco com fermento e a aveia, sem parar de bater.",
      "Incorpore delicadamente as claras em neve.",
      "Asse em forminhas untadas a 180 °C por 40 minutos ou até o palito sair limpo.",
    ],
  },
  {
    id: "bolo-de-amendoim",
    name: "Bolo de Amendoim",
    prepTime: "45 min",
    servings: 4,
    ingredients: [
      "3 ovos",
      "2 colheres (sopa) de manteiga",
      "1 xícara de xylitol",
      "1 e 1/2 xícara de farinha de amendoim (amendoim moído)",
      "1 xícara de farinha de arroz",
      "1 xícara de leite",
      "1 colher (sopa) de fermento em pó",
    ],
    steps: [
      "No liquidificador, bata os ovos, o leite e o xylitol.",
      "Acrescente as farinhas e o fermento. Bata até obter massa homogênea.",
      "Unte uma forma e polvilhe farinha de arroz. Coloque a massa.",
      "Asse em forno pré-aquecido a 180 °C por 35 minutos.",
      "Para a cobertura: leve ao fogo 2 colheres de farinha de amendoim + 3 colheres de água + 2 colheres de xylitol + 1 colher de margarina, mexendo até espessar. Coloque sobre o bolo.",
    ],
  },
  {
    id: "bolo-de-cenoura-chocolate",
    name: "Bolo de Cenoura com Chocolate",
    prepTime: "45 min",
    servings: 4,
    ingredients: [
      "1 cenoura pequena picada",
      "1 ovo",
      "1 colher (sopa) de óleo de coco",
      "1 colher (chá) de essência de baunilha",
      "100 g de farinha de aveia",
      "4 colheres (sopa) de xylitol",
      "1 colher (sopa) de manteiga",
      "1 colher (sopa) de cacau em pó 100%",
      "50 g de chocolate 70% cacau",
      "1 colher (sopa) de pasta de amendoim",
      "2 colheres (sopa) de água",
    ],
    steps: [
      "Bata no liquidificador a cenoura, o ovo, a baunilha e o óleo de coco.",
      "Misture a farinha de aveia com 3 colheres de xylitol. Junte a mistura do liquidificador.",
      "Asse em forma untada a fogo médio por cerca de 20 minutos. Deixe esfriar e esfarele.",
      "Junte a manteiga à massa esfarelada e amasse até formar uma pasta. Modele bolinhas.",
      "Para o recheio: misture a pasta de amendoim + cacau + 1 colher de xylitol + água. Reserve na geladeira. Recheie as bolinhas e congele 15 min.",
      "Banhe as bolinhas em chocolate derretido. Congele mais 5 min e sirva.",
    ],
  },
  {
    id: "bolo-chocolate-frigideira",
    name: "Bolo de Chocolate na Frigideira",
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "4 colheres (sopa) de tapioca",
      "4 colheres (sopa) de néctar de coco",
      "2 colheres (sopa) de farinha de linhaça",
      "2 colheres (sopa) de cacau em pó",
      "1 colher (chá) de bicarbonato de sódio",
      "2 ovos",
    ],
    steps: [
      "Misture todos os ingredientes até obter massa uniforme.",
      "Leve ao fogo médio em frigideira untada. Tampe e cozinhe por 1-2 minutos.",
      "Vire quando a massa estiver consistente e cozinhe por mais 1 minuto.",
      "Sirva com pasta de amendoim.",
    ],
  },
  {
    id: "bolo-fuba-cremoso",
    name: "Bolo de Fubá Cremoso",
    prepTime: "50 min",
    servings: 8,
    ingredients: [
      "1 e 1/2 xícara (chá) de leite desnatado",
      "3/4 xícara (chá) de fubá",
      "1/2 xícara (chá) de adoçante culinário natural",
      "1 colher (chá) de sementes de erva-doce",
      "1 colher (sopa) de margarina light",
      "2 claras em neve",
      "2 gemas",
      "1 colher (chá) de fermento em pó",
    ],
    steps: [
      "Misture o leite, fubá, adoçante, erva-doce e margarina em panela. Leve ao fogo médio, mexendo sempre até engrossar. Deixe esfriar.",
      "Incorpore delicadamente as claras em neve, as gemas e o fermento à mistura fria.",
      "Despeje em forma quadrada (20 cm) untada e polvilhada com fubá.",
      "Asse em forno médio pré-aquecido (180 °C) por 40 minutos ou até dourar. Desenforme morno.",
    ],
  },
  {
    id: "bolo-de-iogurte",
    name: "Bolo de Iogurte",
    prepTime: "45 min",
    servings: 7,
    ingredients: [
      "1 pote (170 g) de iogurte natural",
      "1 xícara de leite desnatado",
      "1/2 xícara de azeite",
      "2 xícaras de adoçante em pó (estévia)",
      "3 xícaras de farinha de coco",
      "1 envelope de fermento em pó",
      "Raspas e suco de 1/2 limão",
      "2 pitadas de canela",
    ],
    steps: [
      "Pré-aqueça o forno a 180 °C. Unte e enfarinhe a forma.",
      "Misture o iogurte, o leite e o azeite até incorporar.",
      "Acrescente a farinha, a canela e misture até obter massa homogênea.",
      "Coloque na forma e asse por 30-45 minutos.",
      "Decore com iogurte e frutas de sua preferência.",
    ],
  },
  {
    id: "bolo-leite-ninho",
    name: "Bolo de Leite em Pó",
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "1 ovo",
      "3 colheres (sopa) de leite em pó",
      "1 colher (sopa) de xylitol",
      "1/2 colher (chá) de fermento em pó",
      "Para a cobertura: 1 colher (chá) de xylitol + 2 colheres (sopa) de água quente + 3 gotas de baunilha",
    ],
    steps: [
      "Em uma caneca, bata o ovo com 2 colheres de leite em pó e o xylitol com um garfo.",
      "Acrescente o fermento e misture.",
      "Leve ao microondas em potência máxima por 3 min e meio.",
      "Prepare a cobertura misturando o leite em pó restante com xylitol, baunilha e água quente. Despeje sobre o bolo.",
    ],
  },
  {
    id: "bolo-de-maizena",
    name: "Bolo de Maizena",
    prepTime: "45 min",
    servings: 8,
    ingredients: [
      "280 g de maizena",
      "1 colher (chá) de fermento químico",
      "1 colher (chá) de estévia em pó",
      "100 ml de leite",
      "1 pote (125 g) de iogurte natural sem açúcar",
      "125 ml de óleo de girassol",
      "1 colher (chá) de essência de baunilha",
      "4 ovos",
    ],
    steps: [
      "Bata os ovos com fouet ou batedeira.",
      "Acrescente a estévia, o leite, o óleo, a baunilha e o iogurte. Misture bem.",
      "Incorpore a maizena e o fermento peneirados. Mexa até obter massa leve.",
      "Coloque em forma (20 cm) untada e polvilhada com maizena. Asse a 180 °C por 30 minutos.",
      "Deixe esfriar antes de desenformar.",
    ],
  },
  {
    id: "bolo-de-maracuja",
    name: "Bolo de Maracujá",
    prepTime: "45 min",
    servings: 10,
    ingredients: [
      "2 ovos",
      "1 xícara de xylitol",
      "50 ml de suco concentrado de maracujá",
      "130 g de farinha de aveia",
      "1 colher (chá) de fermento em pó",
      "Para a cobertura: 1/2 xícara de leite em pó + 10 ml de suco de maracujá + 1 colher (chá) de xylitol + 1 colher (sopa) de óleo de coco",
    ],
    steps: [
      "Unte a forma com óleo de coco e polvilhe farinha de aveia.",
      "Bata os ovos, xylitol, óleo de coco e suco. Misture a farinha e o fermento delicadamente.",
      "Asse a 200 °C até dourar.",
      "Prepare a cobertura misturando todos os ingredientes até obter creme. Coloque sobre o bolo desenformado.",
    ],
  },
  {
    id: "bolo-milho-frigideira",
    name: "Bolo de Milho na Frigideira",
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "2 colheres (sopa) de fubá",
      "2 colheres (sopa) de farinha de coco",
      "2 colheres (sopa) de leite vegetal",
      "1 colher (chá) de óleo de coco",
      "1 e 1/2 colheres (sopa) de adoçante culinário natural",
      "2 colheres (sopa) de milho cozido",
      "2 ovos",
      "1 colher (chá) de fermento para bolo",
      "1 pitada de sal",
    ],
    steps: [
      "Bata no liquidificador o leite, o óleo, os ovos, o milho, o adoçante e o sal.",
      "Acrescente o fubá, a farinha de coco e o fermento. Mexa até eliminar os grumos.",
      "Unte frigideira pequena com óleo de coco e coloque a massa. Tampe e cozinhe em fogo baixo.",
      "Quando as beiradas ficarem consistentes, vire e deixe dourar por mais 1 minuto. Polvilhe canela se desejar.",
    ],
  },
  {
    id: "bolo-de-tapioca",
    name: "Bolo de Tapioca",
    prepTime: "1h30",
    servings: 6,
    ingredients: [
      "1 xícara de tapioca granulada",
      "1 xícara de água ou bebida vegetal",
      "2 ovos",
      "2 colheres (sopa) de coco ralado fresco",
      "2 colheres (sopa) de adoçante culinário natural",
      "1 colher (sopa) de óleo de coco derretido",
    ],
    steps: [
      "Hidrate a tapioca na água por 10-20 minutos até ficar consistente.",
      "Bata os ovos com o adoçante, o coco e o óleo de coco. Misture com a tapioca hidratada.",
      "Coloque em forma untada com óleo de coco. Alise e asse a 200 °C por 50 minutos.",
      "Deixe esfriar, desenforme e polvilhe coco ralado.",
    ],
  },
  {
    id: "bombom-de-morango",
    name: "Bombom de Morango",
    prepTime: "30 min",
    servings: 8,
    ingredients: [
      "1 xícara de leite em pó",
      "1 colher (sopa) de nata",
      "1 colher (sopa) de essência de baunilha",
      "1 colher (chá) de xylitol",
      "50 g de chocolate 70%",
      "5 colheres (sopa) de água",
      "Morangos a gosto",
    ],
    steps: [
      "Misture o leite em pó, nata, baunilha, xylitol e água. Amasse com a colher até virar massa moldável.",
      "Com as mãos molhadas, abra a massa, coloque um morango no centro e enrole.",
      "Leve ao congelador por 15 minutos.",
      "Derreta o chocolate, cubra as bolinhas e congele por mais 5 minutos.",
    ],
  },
  {
    id: "brigadeirao-fit",
    name: "Brigadeirão Fit",
    prepTime: "45 min",
    servings: 5,
    ingredients: [
      "1 lata (300 g) de creme de leite",
      "150 g de chocolate 70%",
      "1 sachê de gelatina incolor (12 g)",
      "Óleo de coco para untar",
      "Nibs de cacau para decorar",
    ],
    steps: [
      "Em panela em fogo baixo, derreta o creme de leite com o chocolate formando uma ganache.",
      "Dissolva a gelatina incolor conforme a embalagem. Junte à ganache e misture rapidamente.",
      "Unte bem uma forma para pudim com óleo de coco, coloque a mistura e leve ao congelador por 30 minutos.",
      "Para desenformar, aqueça o fundo da forma no fogão por 10 segundos e vire em um prato.",
      "Decore com nibs de cacau e conserve na geladeira.",
    ],
  },
  {
    id: "brigadeiro-de-aveia",
    name: "Brigadeiro de Aveia",
    prepTime: "45 min",
    servings: 2,
    ingredients: [
      "4 colheres (sopa) de aveia em flocos",
      "1 colher (sopa) de cacau em pó",
      "1 colher (chá) de estévia ou adoçante natural",
      "1 colher (chá) de óleo de coco",
      "100 ml de leite",
      "Chocolate granulado sem açúcar a gosto",
    ],
    steps: [
      "Triture os flocos de aveia até virarem farinha.",
      "Leve ao fogo médio com todos os ingredientes. Mexa até ficar bem espesso.",
      "Retire para um recipiente e deixe esfriar.",
      "Modele em bolinhas e passe no chocolate granulado. Reserve na geladeira.",
    ],
  },
  {
    id: "brownie-de-caneca",
    name: "Brownie de Caneca",
    prepTime: "30 min",
    servings: 2,
    ingredients: [
      "30 g de chocolate 70%",
      "1 colher (sopa) de manteiga",
      "1 ovo",
      "2 colheres (sopa) de xylitol",
      "1 colher (sopa) de farinha de aveia",
      "Para a cobertura: 30 g de coco ralado + 30 ml de água quente + 4 colheres (sopa) de leite em pó + 1 colher (chá) de xylitol",
    ],
    steps: [
      "Separe a clara da gema e bata a clara em neve.",
      "Derreta o chocolate com a manteiga no microondas.",
      "Misture o chocolate derretido com a gema, xylitol, farinha e a clara em neve.",
      "Asse no microondas em potência máxima por 3 minutos (ou em forma pequena no forno).",
      "Para a cobertura: bata no liquidificador a água quente com o leite em pó e xylitol. Misture com o coco. Leve ao congelador por 20 minutos e coloque sobre o brownie.",
    ],
  },
  {
    id: "brownie-de-microondas",
    name: "Brownie de Microondas",
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "1 ovo",
      "1 colher (sopa) de cacau em pó 100%",
      "1 colher (sopa) de pasta de amendoim",
      "2 colheres (sopa) de xylitol",
      "1 colher (sopa) de farinha de coco",
      "30 ml de água quente",
      "Para a cobertura: 1 colher (chá) de pasta de amendoim + nibs de cacau",
    ],
    steps: [
      "Dissolva o cacau na água quente até virar pasta.",
      "Bata no liquidificador o ovo com a pasta de amendoim e o xylitol.",
      "Misture tudo e adicione a farinha de coco.",
      "Asse no microondas por 3 min e meio.",
      "Cubra com pasta de amendoim e nibs de cacau. Sirva quente ou leve à geladeira por 20 minutos.",
    ],
  },
  {
    id: "cajuzinho-uva",
    name: "Cajuzinho com Recheio de Uva",
    prepTime: "15 min",
    servings: 4,
    ingredients: [
      "5 colheres (sopa) de pasta de amendoim integral",
      "2 colheres (sopa) de leite em pó",
      "1 colher (chá) de xylitol",
      "2 colheres (sopa) de água",
      "Uvas inteiras",
    ],
    steps: [
      "Misture a pasta de amendoim, o leite em pó, o xylitol e a água até virar massa.",
      "Abra a massa com a mão, coloque uma uva no centro e feche. Modele em formato de cajuzinho.",
      "Polvilhe leite em pó e leve ao congelador por 10 minutos.",
    ],
  },
  {
    id: "cheesecake-de-limao",
    name: "Cheesecake de Limão",
    prepTime: "1h",
    servings: 5,
    ingredients: [
      "500 g de ricota passada pela peneira",
      "2 colheres (sopa) de farinha de coco",
      "1 xícara (chá) de suco de limão",
      "1 colher (chá) de raspas de limão",
      "3 claras",
      "6 colheres (sopa) de adoçante culinário",
      "3 barras de cereais de maçã com uva-passa",
    ],
    steps: [
      "Misture a ricota, a farinha, o suco e as raspas de limão.",
      "Bata as claras, acrescente o adoçante e bata até obter um suspiro.",
      "Incorpore o suspiro ao creme. Junte as barrinhas de cereal picadas grosseiramente.",
      "Despeje em forma para tortas untada. Asse a 180 °C por 30 minutos.",
      "Deixe esfriar, desenforme e leve à geladeira. Enfeite com raspas de limão.",
    ],
  },
  {
    id: "cheesecake-de-morango",
    name: "Cheesecake de Morango",
    prepTime: "1h30",
    servings: 8,
    ingredients: [
      "300 g de biscoito tipo maisena sem glúten",
      "4 colheres (sopa) de óleo de coco",
      "2 ovos",
      "250 g de tofu orgânico",
      "3 colheres (sopa) de xylitol",
      "1 colher (sopa) de essência de baunilha",
      "Para a calda: 500 g de morango + 10 colheres (sopa) de xylitol + suco de 1/2 limão",
    ],
    steps: [
      "Triture os biscoitos e misture com óleo de coco e 1 ovo até virar farofa moldável. Forre uma forma de aro removível e asse a 180 °C por 5-10 minutos.",
      "Para o recheio: bata o tofu com xylitol e baunilha no liquidificador. Espalhe sobre a base. Asse a 200 °C por 20 min, depois baixe para 180 °C por mais 20 min.",
      "Para a calda: cozinhe os ingredientes em fogo baixo até os morangos ficarem macios. Bata no liquidificador.",
      "Espere esfriar antes de juntar. Leve à geladeira por 1 hora antes de servir.",
    ],
  },
  {
    id: "cookie-banana-aveia",
    name: "Cookie de Banana e Aveia",
    prepTime: "30 min",
    servings: 6,
    ingredients: [
      "1 e 1/2 xícara de aveia em flocos",
      "2 colheres (sopa) de canela (opcional)",
      "1 pitada de sal",
      "2 bananas maduras amassadas",
      "1/2 xícara de purê de maçã natural sem açúcar",
      "1/2 xícara de amêndoa moída",
    ],
    steps: [
      "Misture os ingredientes secos (aveia, amêndoa, canela e sal).",
      "Em outra tigela, misture os ingredientes úmidos (banana e purê de maçã).",
      "Junte os dois e misture bem até obter massa espessa e grudenta.",
      "Modele biscoitos com colheres e coloque em assadeira com papel manteiga.",
      "Asse a 180 °C por 25 minutos. Deixe esfriar sobre uma grade.",
    ],
  },
  {
    id: "creme-gelado-mamao",
    name: "Creme Gelado de Mamão",
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "200 g de mamão em cubos congelados",
      "100 g de sorvete diet de baunilha",
      "1 colher (café) de essência de baunilha (opcional)",
      "1 colher (sopa) de nozes picadas",
    ],
    steps: [
      "Corte o mamão em pedaços e congele 2-3 horas antes.",
      "Coloque no liquidificador o mamão congelado e o sorvete. Bata até virar creme.",
      "Acrescente a essência de baunilha e misture.",
      "Sirva imediatamente polvilhado com nozes.",
    ],
  },
  {
    id: "crepioca-de-banana",
    name: "Crepioca de Banana",
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "1 ovo",
      "2 colheres (sopa) de tapioca",
      "1 banana",
      "1 colher (sopa) de cacau em pó 100%",
      "1 colher (sopa) de xylitol",
      "20 g de chocolate 70%",
    ],
    steps: [
      "Misture o ovo, a tapioca, o cacau e o xylitol até virar massa.",
      "Em frigideira esquentada, coloque a massa, tampe e deixe em fogo baixo até criar bolhas.",
      "Vire e deixe dourar do outro lado.",
      "Coloque a banana no meio, enrole. Derreta o chocolate e jogue por cima.",
    ],
  },
  {
    id: "crepioca-de-chocolate",
    name: "Crepioca de Chocolate",
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "1 ovo",
      "3 colheres (sopa) de tapioca",
      "1 colher (chá) de cacau em pó",
      "1 colher (chá) de xylitol",
      "2 colheres (chá) de creme de leite",
      "20 g de chocolate 70%",
      "3 morangos picados",
    ],
    steps: [
      "Bata o ovo com a tapioca, o cacau e o xylitol.",
      "Despeje em frigideira untada, tampe e cozinhe em fogo baixo até soltar. Vire e doure o outro lado.",
      "Derreta o chocolate com o creme de leite no microondas (20 em 20 segundos). Espalhe na crepioca.",
      "Finalize com os morangos picados.",
    ],
  },
  {
    id: "cupcake-de-banana",
    name: "Cupcake de Banana",
    prepTime: "45 min",
    servings: 6,
    ingredients: [
      "6 bananas maduras",
      "1 xícara de sementes de chia (hidratadas)",
      "1 xícara de flocos de aveia",
      "1 xícara de farinha de amêndoa",
      "1 xícara de coco ralado sem açúcar",
      "1 pitada de sal",
      "Essência de baunilha e estévia a gosto",
    ],
    steps: [
      "Deixe as sementes de chia hidratar em água por 20 minutos.",
      "Transforme as bananas em purê no liquidificador.",
      "Acrescente a aveia, a farinha de amêndoa e misture.",
      "Junte a chia hidratada, o coco, o sal e a estévia. Misture bem.",
      "Distribua em forminhas de cupcake e asse a 180 °C por 20-25 minutos.",
    ],
  },
  {
    id: "doce-de-abobora",
    name: "Doce de Abóbora",
    prepTime: "45 min",
    servings: 6,
    ingredients: [
      "1 abóbora-moranga descascada em pedaços pequenos",
      "1/2 xícara (chá) de adoçante culinário natural",
      "1 xícara (chá) de água",
      "1 pedaço de canela em rama",
    ],
    steps: [
      "Coloque a abóbora, o adoçante, a canela e a água em uma panela.",
      "Cozinhe, mexendo de vez em quando, por 45 minutos até a abóbora ficar bem macia.",
      "Retire do fogo e sirva frio em copinhos ou tigelas.",
    ],
  },
  {
    id: "doce-de-leite-fit",
    name: "Doce de Leite Fit",
    prepTime: "1h30",
    servings: 3,
    ingredients: [
      "200 ml de creme de leite",
      "100 g de xylitol",
      "100 ml de bebida vegetal de coco",
    ],
    steps: [
      "Em panela, junte todos os ingredientes e ligue em fogo baixo.",
      "Fique mexendo sem parar até engrossar bem.",
      "Coloque em pote, deixe esfriar em temperatura ambiente e depois geladeira por 1 hora.",
      "Use direto ou como recheio de bolos e tortas.",
    ],
  },
  {
    id: "doce-de-prestigio-fit",
    name: "Doce de Prestígio Fit",
    prepTime: "15 min",
    servings: 1,
    ingredients: [
      "3 colheres (sopa) de cacau em pó 70%",
      "100 ml de creme de leite fresco",
      "3 colheres (sopa) de leite em pó",
      "2 colheres (sopa) de coco ralado sem açúcar",
      "1 colher (chá) de xylitol",
      "20 ml de água morna",
    ],
    steps: [
      "Em panela em fogo baixo, derreta o creme de leite com o cacau em pó, mexendo até desgrudar.",
      "Reserve 1 colher do chocolate. Coloque o restante na taça e deixe esfriar.",
      "Misture o leite em pó, xylitol, coco e água até virar pasta. Coloque sobre o chocolate.",
      "Leve ao congelador por 10 minutos. Finalize com o chocolate reservado e coco ralado.",
    ],
  },
  {
    id: "donuts-fit",
    name: "Donuts Fit",
    prepTime: "30 min",
    servings: 6,
    ingredients: [
      "1/2 xícara de farinha de amêndoas",
      "8 colheres (chá) de farinha de tapioca",
      "1 colher (chá) de fermento químico",
      "1 pitada de sal",
      "1 ovo pequeno",
      "8 colheres (chá) de néctar de coco",
      "1/4 xícara de leite de coco",
      "1 colher (sopa) de óleo de coco",
    ],
    steps: [
      "Misture os ingredientes secos (farinhas, sal e fermento).",
      "Em outra tigela, misture o ovo, néctar de coco, leite de coco e óleo de coco derretido.",
      "Junte os dois e mexa até ficar uniforme.",
      "Com saco de confeitar, preencha até 2/3 de uma forma de mini donuts untada. Asse a 190 °C por 12 minutos.",
      "Retire do forno, espere 5 minutos e desenforme.",
    ],
  },
  {
    id: "fondue-de-chocolate",
    name: "Fondue de Chocolate",
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "500 ml de leite desnatado",
      "2 colheres (sopa) de cacau em pó",
      "1 colher (chá) de canela em pó",
      "50 g de chocolate 70% ralado",
      "1 colher (sopa) de creme de leite light",
      "200 g de morango para acompanhar",
    ],
    steps: [
      "Em panela, coloque o leite, o cacau e a canela. Cozinhe em fogo baixo sem parar de mexer por 8 minutos até engrossar.",
      "Retire do fogo. Acrescente o chocolate e o creme de leite. Misture.",
      "Despeje em panela de fondue e mantenha em fogo bem baixo. Sirva com morangos.",
    ],
  },
  {
    id: "gelatina-cremosa-morango",
    name: "Gelatina Cremosa de Morango",
    prepTime: "1h",
    servings: 4,
    ingredients: [
      "2 colheres (sopa) de gelatina zero açúcar sabor morango",
      "1 xícara (chá) de água fervente",
      "500 ml de leite desnatado",
      "15 morangos médios fatiados",
      "6 colheres (sopa) de creme de leite pasteurizado",
      "1 colher (sopa) de adoçante culinário natural",
    ],
    steps: [
      "Dissolva a gelatina na água fervente. Misture o leite e os morangos.",
      "Despeje em 4 taças e leve à geladeira por 3 horas.",
      "Bata o creme de leite em velocidade máxima por 2 minutos até montar chantilly. Adicione o adoçante.",
      "Sirva o chantilly sobre a gelatina, decorado com morango e hortelã.",
    ],
  },
  {
    id: "gelatina-de-chocolate",
    name: "Gelatina de Chocolate",
    prepTime: "1h30",
    servings: 4,
    ingredients: [
      "20 g de cacau em pó",
      "8 g de gelatina sem sabor",
      "200 ml de leite de amêndoas",
      "50 g de estévia ou adoçante natural",
    ],
    steps: [
      "Misture o leite de amêndoas com o adoçante e dissolva a gelatina sem sabor.",
      "Acrescente o cacau e mexa muito bem.",
      "Leve ao fogo, mexendo sempre até ferver. Retire e deixe esfriar.",
      "Distribua em forminhas individuais e leve à geladeira por no mínimo 1 hora.",
    ],
  },
  {
    id: "geleia-de-amora",
    name: "Geleia de Amora",
    prepTime: "45 min",
    servings: 4,
    ingredients: [
      "500 g de amora",
      "1 xícara de adoçante culinário natural",
      "Suco de 1 limão",
    ],
    steps: [
      "Lave as amoras e coloque em panela com o adoçante e o suco de limão.",
      "Leve ao fogo médio-baixo por 30 minutos, mexendo de vez em quando, até as amoras ficarem macias e a geleia engrossar.",
      "Se desejar geleia mais lisa, bata no liquidificador e volte ao fogo para engrossar.",
      "Distribua em frascos de vidro e conserve na geladeira.",
    ],
  },
  {
    id: "granola-saudavel",
    name: "Granola Saudável",
    prepTime: "30 min",
    servings: 4,
    ingredients: [
      "200 g de flocos de aveia",
      "150 g de mix de frutos secos (amêndoa, avelã, castanha, noz)",
      "4 colheres (sopa) de sementes de girassol",
      "4 colheres (sopa) de sementes de gergelim",
      "4 colheres (sopa) de xylitol",
      "3 colheres (sopa) de óleo de coco",
    ],
    steps: [
      "Pique os frutos secos em pedaços no processador.",
      "Misture todos os ingredientes secos em uma tigela.",
      "Acrescente o óleo de coco e o xylitol. Misture até ficar granulado.",
      "Espalhe em assadeira com papel manteiga e asse a 180 °C por 20 minutos até dourar.",
      "Deixe esfriar e desgrude com uma colher. Consuma com leite ou iogurte.",
    ],
  },
  {
    id: "leite-condensado-fit",
    name: "Leite Condensado Fit",
    prepTime: "30 min",
    servings: 4,
    ingredients: [
      "1 xícara de leite (240 ml)",
      "1 xícara de leite em pó desnatado",
      "1 xícara de adoçante culinário (Splenda ou similar)",
    ],
    steps: [
      "Bata todos os ingredientes no liquidificador até homogeneizar.",
      "Leve ao fogo baixo, mexendo sempre para não queimar.",
      "Cozinhe por 15 minutos até a mistura ficar amarelada e ao passar a espátula no fundo da panela abrir uma trilha.",
      "Deixe esfriar para obter a consistência desejada. Use em sobremesas.",
    ],
  },
  {
    id: "manjar-calda-laranja",
    name: "Manjar com Calda de Laranja",
    prepTime: "3h",
    servings: 5,
    ingredients: [
      "2 e 1/2 xícaras (chá) de leite desnatado",
      "6 colheres (sopa) de fécula de batata",
      "5 colheres (sopa) de adoçante culinário natural",
      "200 ml de leite de coco light",
      "Para a calda: 2 xícaras de suco de laranja + 3 colheres de adoçante + 3 colheres de fécula de batata + cravos e canela",
    ],
    steps: [
      "Dissolva a fécula em 1/4 xícara de leite frio. Cozinhe o restante do leite, leite de coco, adoçante e fécula em fogo baixo, mexendo até engrossar.",
      "Coloque em forma untada, cubra com filme plástico, deixe esfriar e leve à geladeira por 2 horas.",
      "Para a calda: dissolva a fécula no suco de laranja, adicione os demais ingredientes e cozinhe em fogo baixo até engrossar.",
      "Desenforme o manjar e sirva com a calda de laranja.",
    ],
  },
  {
    id: "maria-mole-fit",
    name: "Maria Mole Fit",
    prepTime: "45 min",
    servings: 3,
    ingredients: [
      "1 envelope de gelatina diet sem sabor",
      "1 xícara de água quente + 1 xícara de água fria",
      "1 colher (sopa) de adoçante culinário natural",
      "50 g de coco ralado sem açúcar",
      "1 copo de iogurte desnatado natural",
      "2 colheres (sopa) de leite de coco",
    ],
    steps: [
      "Hidrate a gelatina na água quente e acrescente a água fria. Leve ao congelador por 30 minutos.",
      "Bata no liquidificador a gelatina firme com o leite de coco, iogurte e adoçante por poucos segundos.",
      "Despeje em forma untada e leve à geladeira até firmar.",
      "Corte em quadrados e passe no coco ralado.",
    ],
  },
  {
    id: "mini-torta-holandesa",
    name: "Mini Torta Holandesa",
    prepTime: "30 min",
    servings: 2,
    ingredients: [
      "150 g de castanha de caju",
      "1 colher (chá) de manteiga",
      "1 colher (chá) de xylitol",
      "5 colheres (sopa) de leite em pó desnatado",
      "20 ml de água quente",
      "1 colher (sopa) de xylitol",
      "1 colher (sopa) de creme de leite",
      "5 gotas de essência de baunilha",
      "40 g de chocolate 70%",
    ],
    steps: [
      "Triture as castanhas no processador. Junte a manteiga e 1 colher de xylitol e bata até virar massa. Modele em forminhas e congele.",
      "Para o recheio: bata no liquidificador o leite em pó com a água quente. Leve ao fogo baixo com xylitol, creme de leite e baunilha, mexendo até desgrudar.",
      "Coloque o creme branco sobre a base congelada e congele por 20 minutos.",
      "Derreta o chocolate e jogue por cima. Congele mais 10 minutos e sirva.",
    ],
  },
  {
    id: "mousse-de-abacate",
    name: "Mousse de Abacate",
    prepTime: "1h30",
    servings: 2,
    ingredients: [
      "1 abacate maduro",
      "1 pote (170 g) de iogurte natural",
      "2 colheres (sopa) de xylitol",
      "2 quadrados de chocolate 70% cacau",
      "10 gotas de essência de baunilha",
    ],
    steps: [
      "Bata o abacate com o iogurte.",
      "Acrescente o xylitol, o chocolate e a baunilha. Bata novamente.",
      "Coloque em tacinhas e leve à geladeira por 2 horas (ou ao congelador por 1h30 para consistência de sorvete).",
    ],
  },
  {
    id: "mousse-de-chia-chocolate",
    name: "Mousse de Chia e Chocolate",
    prepTime: "45 min",
    servings: 6,
    ingredients: [
      "6 colheres (sopa) de sementes de chia",
      "350 ml de água ou leite morno",
      "5 colheres (sopa) de cacau em pó",
      "8 tâmaras secas sem caroço",
    ],
    steps: [
      "Deixe a chia hidratar no leite/água por algumas horas. Hidrate as tâmaras em água fervente por 15 minutos.",
      "Bata as tâmaras no processador até ficarem em pedaços pequenos.",
      "Acrescente a chia hidratada e bata por 1-2 minutos.",
      "Adicione o cacau e bata até incorporar. Leve à geladeira por 30 minutos.",
    ],
  },
  {
    id: "mousse-de-chocolate",
    name: "Mousse de Chocolate",
    prepTime: "45 min",
    servings: 2,
    ingredients: [
      "1 vidro de leite de coco",
      "50 g de chocolate 70%",
      "10 gotas de baunilha",
      "1 colher (chá) de xylitol",
      "2 gemas",
    ],
    steps: [
      "Em panela, mexa o leite de coco com as gemas em fogo médio por 4 minutos até engrossar.",
      "No liquidificador, junte o creme quente, o chocolate picado e o xylitol. Bata por 1 minuto.",
      "Coloque em taças e leve ao congelador por 30 minutos ou à geladeira por 1h30.",
    ],
  },
  {
    id: "mousse-de-limao",
    name: "Mousse de Limão",
    prepTime: "40 min",
    servings: 4,
    ingredients: [
      "3 claras",
      "1 pote (170 g) de iogurte natural integral",
      "1 sachê de gelatina incolor",
      "Suco e raspas de 1 limão",
      "3 colheres (sopa) de xylitol",
      "5 gotas de essência de baunilha",
    ],
    steps: [
      "Bata as claras em ponto de neve.",
      "Acrescente o iogurte, xylitol e suco de limão. Misture delicadamente.",
      "Dissolva a gelatina conforme a embalagem e adicione com a baunilha.",
      "Coloque em taças e leve ao congelador por 20 minutos ou à geladeira por 1 hora. Finalize com raspas de limão.",
    ],
  },
  {
    id: "mousse-de-maracuja",
    name: "Mousse de Maracujá",
    prepTime: "45 min",
    servings: 3,
    ingredients: [
      "1 pacote de gelatina de maracujá zero açúcar",
      "400 ml de água quente",
      "1 pote de iogurte natural sem açúcar",
      "1 colher (chá) de xylitol",
    ],
    steps: [
      "Dissolva a gelatina em 400 ml de água quente e deixe esfriar.",
      "Bata no liquidificador com o iogurte e xylitol por 2 minutos.",
      "Coloque em taças e leve ao congelador por 20-30 minutos até solidificar.",
      "Conserve na geladeira.",
    ],
  },
  {
    id: "muffin-cenoura-chocolate",
    name: "Muffin de Cenoura com Chocolate",
    prepTime: "15 min",
    servings: 6,
    ingredients: [
      "1 cenoura média",
      "2 ovos",
      "1 xícara de farinha de aveia",
      "1 colher (sopa) de óleo de coco",
      "3 colheres (sopa) de xylitol",
      "1 colher (chá) de fermento para bolo",
      "Chocolate 85% a gosto",
    ],
    steps: [
      "Bata no liquidificador a cenoura, os ovos e o óleo de coco até obter creme liso.",
      "Misture a farinha e o xylitol. Junte a mistura do liquidificador. Acrescente o fermento.",
      "Coloque em forminhas de silicone, adicione pedaços de chocolate por cima.",
      "Asse no microondas por 4 minutos em potência máxima. Deixe esfriar e sirva.",
    ],
  },
  {
    id: "nutella-caseira",
    name: "Nutella Caseira",
    prepTime: "15 min",
    servings: 4,
    ingredients: [
      "2 xícaras de avelãs torradas sem pele",
      "1/4 xícara de leite integral ou de amêndoas",
      "1/4 xícara de cacau em pó",
      "2 colheres (sopa) de essência de baunilha",
      "1 e 1/2 colheres (sopa) de estévia",
      "1 colher (café) de sal",
    ],
    steps: [
      "Bata as avelãs no processador até virar purê cremoso (paciência — elas passam por farinha, farofa e depois creme).",
      "Acrescente o cacau, a baunilha, a estévia, o sal e o leite. Bata até incorporar completamente.",
      "Sirva em seguida ou conserve na geladeira.",
    ],
  },
  {
    id: "pacoca-caseira",
    name: "Paçoca Caseira",
    prepTime: "10 min",
    servings: 5,
    ingredients: [
      "6 colheres (sopa) de amendoim sem casca torrado",
      "4 colheres (sopa) de leite em pó desnatado",
      "1 xícara de proteína de soja texturizada torrada",
      "4 colheres (sopa) de adoçante culinário natural",
      "1 pitada de sal",
    ],
    steps: [
      "Bata todos os ingredientes no liquidificador até formar uma farofa.",
      "Coloque em pote com tampa fechada.",
      "Na hora de servir, distribua em copinhos ou forminhas.",
    ],
  },
  {
    id: "panna-cotta-italiana",
    name: "Panna Cotta Italiana",
    prepTime: "4h",
    servings: 4,
    ingredients: [
      "600 ml de leite de coco",
      "1 colher (chá) de adoçante culinário natural",
      "1/2 fava de baunilha (ou 1 colher de essência)",
      "10 g de gelatina em pó",
      "Para o coulis: 1 xícara de morangos + 1 colher de adoçante + 1 colher de suco de limão",
    ],
    steps: [
      "Hidrate a gelatina em um pouco de água fria. Aqueça o leite de coco com adoçante e baunilha até ferver.",
      "Retire do fogo, coloque em banho-maria invertido para esfriar. Quando morno, acrescente a gelatina e dissolva.",
      "Distribua em potinhos, cubra com filme e leve à geladeira por 4 horas.",
      "Para o coulis: cozinhe os ingredientes em fogo médio-alto até ferver e engrossar. Bata e reserve na geladeira.",
      "Desenforme e sirva com o coulis.",
    ],
  },
  {
    id: "pave-de-abacaxi",
    name: "Pavê de Abacaxi",
    prepTime: "3h",
    servings: 4,
    ingredients: [
      "200 g de abacaxi picado",
      "30 g de adoçante culinário",
      "150 ml de água",
      "2 colheres de fécula de batata",
      "100 ml de gemas desidratadas",
      "40 g de adoçante",
      "400 ml de leite desnatado morno",
      "100 g de coco fresco ralado",
      "Base: 100 g de farinha de coco + 60 ml de gema + 30 g de adoçante + 3 claras em neve + 1 colher de fermento",
    ],
    steps: [
      "Calda: cozinhe o abacaxi com o adoçante e a água por 10 minutos. Reserve.",
      "Creme: misture a gema, adoçante, leite e fécula em fogo baixo até engrossar. Junte o abacaxi sem a calda.",
      "Base: misture as gemas, adoçante, farinha e fermento. Incorpore as claras em neve. Asse a 200 °C por 8-10 minutos. Umedeça com a calda.",
      "Monte: camadas de base + creme. Leve à geladeira por 2 horas. Decore com coco ralado.",
    ],
  },
  {
    id: "pave-de-baunilha",
    name: "Pavê de Baunilha",
    prepTime: "3h",
    servings: 4,
    ingredients: [
      "300 ml de leite integral",
      "5 colheres (sopa) de fécula de batata",
      "3 colheres (sopa) de xylitol",
      "10 gotas de essência de baunilha",
      "Uvas e morangos picados para decorar",
    ],
    steps: [
      "Dissolva a fécula no leite e coloque em panela com o xylitol.",
      "Mexa em fogo baixo até engrossar. Desligue e acrescente a baunilha.",
      "Deixe esfriar. Monte o pavê com o creme e as frutas.",
      "Leve à geladeira por no mínimo 3 horas antes de servir.",
    ],
  },
  {
    id: "pe-de-moca",
    name: "Pé de Moça",
    prepTime: "40 min",
    servings: 4,
    ingredients: [
      "200 ml de creme de leite",
      "80 g de amendoim torrado sem pele e sem sal",
      "1 colher (chá) de xylitol",
      "1 pitada de sal",
    ],
    steps: [
      "Em panela em fogo baixo, junte o creme de leite e o xylitol. Mexa até engrossar.",
      "Acrescente o amendoim e o sal. Misture bem.",
      "Deixe esfriar e leve 30 minutos ao congelador.",
      "Com as mãos molhadas, modele no formato desejado e passe em xylitol.",
    ],
  },
  {
    id: "pera-caramelizada",
    name: "Pera Caramelizada",
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "1 pera em fatias",
      "1 colher (café) de óleo de coco",
      "1 colher (chá) de xylitol",
      "1 colher (sopa) de pasta de amendoim",
      "Canela a gosto",
    ],
    steps: [
      "Em frigideira, derreta o óleo de coco e doure as fatias de pera em fogo alto por 1 minuto.",
      "Vire, acrescente o xylitol e doure o outro lado por mais 1 minuto.",
      "Polvilhe canela e finalize com pasta de amendoim.",
    ],
  },
  {
    id: "picole-de-morango",
    name: "Picolé Cremoso de Morango",
    prepTime: "4h",
    servings: 3,
    ingredients: [
      "200 g de morangos frescos",
      "200 ml de iogurte natural sem açúcar",
      "2 envelopes de adoçante natural culinário",
    ],
    steps: [
      "Bata os morangos com o adoçante no liquidificador até virar purê.",
      "Misture com o iogurte.",
      "Coloque em forminhas de picolé e congele por no mínimo 2 horas.",
    ],
  },
  {
    id: "pipoca-chocolate-amargo",
    name: "Pipoca com Chocolate Amargo",
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "2 colheres (sopa) de milho de pipoca",
      "50 g de chocolate 70%",
    ],
    steps: [
      "Coloque o milho em recipiente fundo que possa ir ao microondas. Tampe e asse por até 5 minutos em potência máxima.",
      "Derreta o chocolate, deixe esfriar um pouco.",
      "Derrame o chocolate sobre a pipoca aos poucos e misture bem.",
    ],
  },
  {
    id: "pudim-de-banana",
    name: "Pudim de Banana Nanica",
    prepTime: "30 min",
    servings: 4,
    ingredients: [
      "2 bananas nanicas maduras",
      "2 ovos",
      "2 colheres (sopa) de farinha de aveia",
      "Gotas de cacau a gosto",
    ],
    steps: [
      "Bata os ovos, a farinha de aveia e as bananas no liquidificador por 30 segundos.",
      "Despeje em forma untada. Distribua gotas de cacau por cima.",
      "Asse a 180 °C por 20 minutos.",
      "Deixe esfriar por 1-2 horas antes de servir.",
    ],
  },
  {
    id: "pudim-de-chia",
    name: "Pudim de Chia",
    prepTime: "24h",
    servings: 1,
    ingredients: [
      "2 colheres (sopa) de sementes de chia",
      "150 ml de leite de coco ou de amêndoas",
      "1 colher (sopa) de xylitol",
      "10 gotas de essência de baunilha",
      "Frutas a gosto",
    ],
    steps: [
      "Coloque a chia no copo em que irá servir.",
      "Acrescente o leite, o xylitol e a baunilha. Misture.",
      "Leve à geladeira de um dia para o outro.",
      "Finalize com frutas a gosto.",
    ],
  },
  {
    id: "pudim-flan",
    name: "Pudim Flan",
    prepTime: "30 min",
    servings: 4,
    ingredients: [
      "6 ovos",
      "200 g de cream cheese light",
      "200 ml de leite desnatado",
      "1 colher (chá) de essência de baunilha",
      "6 envelopes de stevia",
      "100 g de adoçante em pó culinário para forno e fogão (para o caramelo)",
    ],
    steps: [
      "Em frigideira, derreta o adoçante em pó para forno/fogão até virar caramelo. Verta na forma de pudim.",
      "Bata no liquidificador os ovos, o cream cheese, o leite e a baunilha por 1 minuto. Acrescente a stevia.",
      "Coloque a mistura sobre o caramelo na forma e asse a 165 °C por 15 minutos ou até firmar.",
      "Desenforme e sirva.",
    ],
  },
  {
    id: "queijadinha-de-laranja",
    name: "Queijadinha de Laranja",
    prepTime: "30 min",
    servings: 3,
    ingredients: [
      "4 ovos",
      "200 ml de leite desnatado",
      "1 colher (sopa) de adoçante natural em pó",
      "1 colher (sopa) de margarina light",
      "1 ricota fresca picada",
      "1/2 xícara (chá) de farinha de coco",
      "1 colher (sopa) de fermento em pó",
      "400 ml de suco de laranja integral",
    ],
    steps: [
      "No liquidificador, bata os ovos, o suco, o leite, o adoçante, a margarina e a ricota até homogeneizar.",
      "Misture a farinha de coco e o fermento com colher.",
      "Distribua em forminhas de papel dentro de forminhas de empada. Asse em forno médio por 20 minutos até dourar.",
      "Decore com calda de laranja e sirva.",
    ],
  },
  {
    id: "rabanada-saudavel",
    name: "Rabanada Saudável",
    prepTime: "30 min",
    servings: 1,
    ingredients: [
      "2 fatias de pão integral",
      "1 clara de ovo",
      "1 envelope de adoçante sem calorias",
      "1 pitada de canela em pó",
      "3 gotas de essência de baunilha",
      "50 ml de leite desnatado",
      "1 fio de óleo de canola",
      "Néctar de coco para acompanhar",
    ],
    steps: [
      "Bata a clara com o adoçante, a baunilha e a canela. Acrescente o leite.",
      "Mergulhe as fatias de pão na mistura de clara, cobrindo os dois lados.",
      "Aqueça a frigideira com o óleo e cozinhe as fatias por 3 minutos de cada lado até dourar.",
      "Sirva acompanhado de néctar de coco.",
    ],
  },
  {
    id: "salame-de-chocolate",
    name: "Salame de Chocolate",
    prepTime: "4h",
    servings: 6,
    ingredients: [
      "200 g de chocolate 70% derretido",
      "1 colher (sopa) de manteiga",
      "60 g de biscoito maisena ou água e sal",
      "40 g de nozes (ou avelãs/amêndoas)",
      "2 gotas de essência de laranja (opcional)",
    ],
    steps: [
      "Derreta o chocolate com a manteiga em banho-maria ou microondas.",
      "Pique as nozes e parta os biscoitos em pedaços pequenos.",
      "Misture tudo ao chocolate derretido. Acrescente a essência de laranja se desejar.",
      "Coloque sobre papel-alumínio untado e enrole firmemente, fechando as pontas.",
      "Reserve no congelador por 4 horas. Retire 30 minutos antes de servir.",
    ],
  },
  {
    id: "sonho-de-valsa-fit",
    name: "Sonho de Valsa Fit",
    prepTime: "20 min",
    servings: 4,
    ingredients: [
      "100 g de farinha de amêndoas",
      "100 g de farinha de amendoim",
      "20 g de manteiga em temperatura ambiente",
      "1 colher (sopa) de xylitol",
      "30 g de chocolate 70%",
    ],
    steps: [
      "Misture as farinhas, a manteiga e o xylitol. Amasse até formar uma massa.",
      "Modele bolinhas e leve ao congelador por 15 minutos.",
      "Derreta o chocolate no microondas (20 em 20 segundos).",
      "Banhe as bolinhas no chocolate e leve ao congelador por mais 5 minutos. Conserve na geladeira.",
    ],
  },
  {
    id: "sorvete-de-cafe",
    name: "Sorvete de Café",
    prepTime: "6h",
    servings: 4,
    ingredients: [
      "2 colheres (sopa) de cream cheese light",
      "1 xícara de iogurte light",
      "3 colheres (café) de stevia",
      "1 xícara de café preparado",
      "Raspas de chocolate 70%",
    ],
    steps: [
      "Bata no liquidificador o cream cheese com o café por 3 minutos.",
      "Acrescente o iogurte e a stevia. Prove e ajuste o doce.",
      "Congele em recipiente por 1 hora, bata novamente e retorne ao freezer por 5-6 horas.",
      "Sirva com raspas de chocolate.",
    ],
  },
  {
    id: "sorvete-de-chocolate-banana",
    name: "Sorvete de Chocolate de Banana",
    prepTime: "6h",
    servings: 2,
    ingredients: [
      "2 bananas em rodelas congeladas (mínimo 6 horas)",
      "2 colheres (sopa) de cacau em pó 100%",
      "2 colheres (sopa) de bebida vegetal (opcional)",
    ],
    steps: [
      "Congele as bananas em rodelas por no mínimo 6 horas.",
      "Bata as bananas congeladas com o cacau no processador até ficar cremoso.",
      "Se precisar, acrescente a bebida vegetal.",
      "Consuma imediatamente se preferir cremoso, ou congele por mais 2-3 horas para consistência mais firme.",
    ],
  },
  {
    id: "sorvete-iogurte-frutas",
    name: "Sorvete de Iogurte com Frutas",
    prepTime: "4h",
    servings: 3,
    ingredients: [
      "250 g de iogurte grego magro",
      "4 morangos",
      "1 kiwi",
      "1 manga",
      "1 colher (sopa) de néctar de coco",
    ],
    steps: [
      "Corte os morangos, descasque e cube o kiwi e a manga.",
      "Misture o iogurte com o néctar de coco até incorporar.",
      "Distribua o iogurte por forminhas e cubra com as frutas misturadas.",
      "Congele por no mínimo 2 horas. Consuma rapidamente após retirar do freezer.",
    ],
  },
  {
    id: "sorvete-de-morango",
    name: "Sorvete de Morango",
    prepTime: "10 min",
    servings: 2,
    ingredients: [
      "1 pacote de gelatina de morango zero açúcar",
      "300 ml de água quente",
      "5 colheres (sopa) de leite em pó desnatado",
      "12 pedras de gelo",
    ],
    steps: [
      "Dissolva a gelatina na água quente.",
      "Coloque no liquidificador com o leite em pó e o gelo.",
      "Bata em velocidade alta até virar creme.",
      "Sirva imediatamente.",
    ],
  },
  {
    id: "sorvete-de-pessego",
    name: "Sorvete de Pêssego",
    prepTime: "10 min",
    servings: 3,
    ingredients: [
      "2 latas de pêssego congelado",
      "1/4 copo de leite de coco",
    ],
    steps: [
      "Coloque os pêssegos congelados no liquidificador e bata até virar polpa.",
      "Adicione o leite de coco e bata até ficar cremoso.",
      "Coloque nas taças e decore com pedaços de pêssego e hortelã.",
    ],
  },
  {
    id: "sorvete-de-pitaya",
    name: "Sorvete de Pitaya",
    prepTime: "10 min",
    servings: 2,
    ingredients: [
      "2 pitayas descascadas, cortadas e congeladas",
      "1 colher (sopa) de xylitol",
      "1 colher (sopa) de leite em pó",
    ],
    steps: [
      "Retire as pitayas do congelador 10 minutos antes.",
      "Bata no processador com os demais ingredientes até ficar cremoso.",
      "Sirva imediatamente.",
    ],
  },
  {
    id: "sufle-de-chocolate",
    name: "Suflê de Chocolate",
    prepTime: "30 min",
    servings: 8,
    ingredients: [
      "250 g de chocolate meio amargo 75% cacau",
      "5 gemas de ovo",
      "100 g de creme de leite",
      "20 ml de leite desnatado",
    ],
    steps: [
      "Derreta o chocolate no microondas até ficar completamente líquido.",
      "Acrescente o leite e o creme de leite. Misture bem.",
      "Adicione as gemas mexendo sempre.",
      "Distribua em forminhas que possam ir ao forno e asse a 165 °C por 20 minutos.",
      "Desenforme e sirva.",
    ],
  },
  {
    id: "suspiro-sem-acucar",
    name: "Suspiro",
    prepTime: "1h",
    servings: 2,
    ingredients: [
      "3 ovos (claras)",
      "4 colheres (sopa) de adoçante (aspartame ou similar)",
    ],
    steps: [
      "Separe as claras das gemas.",
      "Bata as claras em ponto de neve com batedeira elétrica. Acrescente o adoçante e bata até obter merengue firme.",
      "Com saco de confeitar, coloque pequenas porções em assadeira.",
      "Asse em forno a 100 °C com a porta entreaberta por 40 minutos.",
      "Deixe esfriar em temperatura ambiente.",
    ],
  },
  {
    id: "tapioca-banana",
    name: "Tapioca com Banana",
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "3 colheres (sopa) de tapioca",
      "1 banana maçã",
      "1 colher (sopa) de leite em pó",
      "1 colher (sopa) de água",
      "1 colher (chá) de xylitol",
    ],
    steps: [
      "Em frigideira em fogo médio, coloque a tapioca e aguarde ficar pronta (soltando nas beiradas).",
      "Para o creme: dissolva o leite em pó na água e acrescente o xylitol.",
      "Fatie a banana e coloque sobre a tapioca pronta. Finalize com o creme.",
    ],
  },
  {
    id: "torrone-fit",
    name: "Torrone Fit",
    prepTime: "2h30",
    servings: 5,
    ingredients: [
      "2 xícaras (chá) de aveia em flocos",
      "6 colheres (sopa) de cacau em pó sem açúcar",
      "2 colheres (sopa) de adoçante culinário natural",
      "8 colheres (sopa) de leite desnatado",
      "200 g de manteiga light",
      "1 pacote de biscoito integral com gergelim",
    ],
    steps: [
      "Em panela, adicione a aveia, o adoçante e o cacau. Acrescente o leite e a manteiga aos poucos, mexendo até homogeneizar. Leve ao fogo brando até a manteiga derreter.",
      "Em travessa, alterne camadas de creme e biscoito, terminando com creme.",
      "Cubra com papel-alumínio e leve à geladeira por pelo menos 2 horas.",
      "Corte em pedaços e sirva.",
    ],
  },
  {
    id: "torta-de-chocolate-fit",
    name: "Torta de Chocolate Fit",
    prepTime: "45 min",
    servings: 4,
    ingredients: [
      "50 g de coco ralado sem açúcar",
      "1 clara de ovo",
      "2 colheres (sopa) de xylitol",
      "100 g de chocolate 70%",
      "2 colheres (sopa) de creme de leite",
      "Nibs de cacau a gosto",
    ],
    steps: [
      "Misture o coco ralado com a clara e o xylitol até obter farofa úmida.",
      "Espalhe em forma pequena desmontável e asse até dourar. Deixe esfriar.",
      "Derreta o chocolate, junte o creme de leite e misture. Espalhe sobre a base.",
      "Polvilhe nibs de cacau e leve ao congelador por 20 minutos.",
    ],
  },
  {
    id: "torta-de-maca",
    name: "Torta de Maçã",
    prepTime: "1h30",
    servings: 6,
    ingredients: [
      "Para a massa: 2 xícaras de farinha de coco + 3/4 xícara de água fervente + 1/4 xícara de óleo + 1 colher (chá) de fermento + pitada de sal",
      "Para o recheio: 8 maçãs fuji + 1 colher (chá) de canela em pó",
    ],
    steps: [
      "Misture os ingredientes secos da massa, adicione os líquidos e amasse até ficar lisa. Deixe descansar 30 minutos na geladeira.",
      "Forre uma forma de torta com a massa e pique o fundo. Asse a 180 °C por 20-40 minutos até crocante.",
      "Descasque e cozinhe 6 maçãs em cubos tampadas até ficarem macias. Adicione canela e reduza a purê.",
      "Espalhe o purê sobre a massa. Decore com as 2 maçãs restantes em fatias. Asse a 180 °C por 20 minutos.",
    ],
  },
  {
    id: "torta-de-morango",
    name: "Torta de Morango",
    prepTime: "4h",
    servings: 8,
    ingredients: [
      "Para a massa: 180 g de farinha de coco + 80 g de manteiga + 1 colher (chá) de xylitol + 2 gemas + raspas de limão",
      "Para a cobertura: 400 g de morangos + 1 envelope de gelatina de morango light",
      "Para o creme: 300 g de chantilly light + 1 colher (chá) de xylitol",
    ],
    steps: [
      "Misture os ingredientes da massa e amasse até formar uma bola. Refrigere por 30 minutos.",
      "Forre uma forma de torta com a massa. Asse a 180 °C por 15 minutos até dourar.",
      "Prepare a gelatina conforme a embalagem e reserve na geladeira para firmar levemente.",
      "Bata o chantilly com o xylitol e recheie a base fria.",
      "Decore com morangos e cubra com a gelatina semi-firme. Refrigere por 3 horas.",
    ],
  },
  {
    id: "torta-gelada-frutas-vermelhas",
    name: "Torta Gelada de Frutas Vermelhas",
    prepTime: "2h30",
    servings: 8,
    ingredients: [
      "Para a base: 200 g de biscoito digestivo + 100 g de margarina light",
      "Para o creme: 400 g de ricota fresca light + 1 pote de iogurte desnatado + 2 ovos + 2 colheres de adoçante",
      "Para a calda: 2 xícaras de mix de frutas vermelhas + 3 colheres de adoçante",
    ],
    steps: [
      "Triture os biscoitos e misture com a margarina. Forre fundo e laterais de forma removível. Refrigere.",
      "Bata na batedeira os ovos e o adoçante. Acrescente a ricota, o iogurte e misture.",
      "Despeje sobre a base e asse a 180 °C por 40 minutos. Deixe esfriar sem desenformar.",
      "Cozinhe as frutas com o adoçante até a calda engrossar. Refrigere separado.",
      "Leve a torta à geladeira por 2 horas. Desenforme, cubra com a calda e sirva.",
    ],
  },
  {
    id: "tortinha-de-banana",
    name: "Tortinha de Banana",
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "50 g de amêndoas torradas sem sal",
      "1 colher (chá) de manteiga",
      "3 colheres (chá) de xylitol",
      "2 bananas congeladas",
      "1 colher (sopa) de leite em pó",
      "30 g de chocolate 85%",
    ],
    steps: [
      "Bata as amêndoas com a manteiga e o xylitol no processador. Modele em forminhas de silicone. Congele.",
      "Bata as bananas congeladas com o leite em pó até virar creme de sorvete.",
      "Recheie as forminhas com o creme de banana.",
      "Derreta o chocolate e jogue por cima. Sirva.",
    ],
  },
  {
    id: "tortinha-doce-de-leite",
    name: "Tortinha de Doce de Leite",
    prepTime: "30 min",
    servings: 2,
    ingredients: [
      "100 g de farinha de amêndoas",
      "1 colher (sopa) de manteiga em temperatura ambiente",
      "200 ml de creme de leite",
      "4 colheres (chá) de stevia",
      "1 colher (chá) de essência de baunilha",
    ],
    steps: [
      "Amasse a farinha de amêndoas com a manteiga até formar massa. Modele em forminhas de silicone e asse a 180 °C até dourar.",
      "Em panela, cozinhe o creme de leite com a stevia e a baunilha em fogo baixo, mexendo até engrossar como doce de leite.",
      "Deixe a base e o recheio esfriarem. Monte, decore com amêndoas trituradas e leve à geladeira.",
    ],
  },
  {
    id: "trufa-de-banana",
    name: "Trufa de Banana",
    prepTime: "30 min",
    servings: 5,
    ingredients: [
      "1 banana nanica",
      "6 colheres (sopa) de leite em pó desnatado",
      "3 colheres (sopa) de cacau em pó 70%",
    ],
    steps: [
      "Amasse a banana com o garfo e leve ao microondas por 1 minuto.",
      "Junte o leite em pó e o cacau. Misture bem.",
      "Leve ao congelador por 20 minutos.",
      "Enrole em bolinhas e passe no cacau em pó. Conserve na geladeira.",
    ],
  },
  {
    id: "pessego-grelhado-iogurte",
    name: "Pêssego Grelhado com Iogurte",
    prepTime: "30 min",
    servings: 2,
    ingredients: [
      "2 pêssegos",
      "4 colheres (sopa) de iogurte grego natural",
      "Canela em pó a gosto",
      "4 folhas de hortelã",
    ],
    steps: [
      "Corte os pêssegos ao meio, retire o caroço e deixe em água gelada por 15 minutos.",
      "Polvilhe canela na polpa.",
      "Grelhe com a polpa virada para baixo por 10-15 minutos até dourar.",
      "Recheie com o iogurte, insira folha de hortelã e polvilhe mais canela.",
    ],
  },
];

export const LIBRARY_CATEGORIES: LibraryCategory[] = [
  {
    id: "pratos-principais",
    label: "Pratos Principais",
    emoji: "🍽️",
    recipes: pratosPrincipais,
  },
  {
    id: "sopas-caldos",
    label: "Sopas e Caldos",
    emoji: "🍲",
    recipes: [],
  },
  {
    id: "lanches",
    label: "Lanches",
    emoji: "🥪",
    recipes: [],
  },
  {
    id: "paes-salgados",
    label: "Pães e Salgados",
    emoji: "🥐",
    recipes: [],
  },
  {
    id: "doces-sobremesas",
    label: "Doces e Sobremesas",
    emoji: "🍰",
    recipes: docesSemAcucar,
  },
  {
    id: "fitness-funcionais",
    label: "Fitness, Diet e Funcionais",
    emoji: "💪",
    recipes: [],
  },
  {
    id: "alimentacao-infantil",
    label: "Alimentação Infantil e Papinhas",
    emoji: "👶",
    recipes: [],
  },
];

